name: expensemanager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^5.4.0
  intl: ^0.19.0
  gif_view: ^0.4.4
  curved_navigation_bar: ^1.0.6
  fluttertoast: ^8.2.6
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
  